apiVersion: v1
imagePullSecrets:
  - name: dockersecret
kind: ServiceAccount
metadata:
  creationTimestamp: '2020-06-23T16:50:36Z'
  name: default
  namespace: default
  uid: a9907ff2-b571-11ea-a961-42010a8a01c0
secrets:
  - name: default-token-n6xxj
